### ISSUE TITLE
maxwell2d.post.get_solution_data doesn't work

### ISSUE THREAD

**Issue by mehs1006** [ansys/pyaedt#6568]
### Before submitting the issue

- [x] I have searched among the existing issues
- [ ] I am using a Python virtual environment

### Description of the bug

Hi,

The code works perfectly in the previous version pyaedt==0.15.0.
I updated to pyaedt==0.18.0 yesterday, and the error happened.
**AttributeError: 'bool' object has no attribute 'data_real'**

Please guide me on how to fix it.
Thank you.

Best,
//MeHs

### Steps To Reproduce

I use the code below to get the time-varying induced voltage data from AEDT Maxwell R2025R2.
```
Dict_vari = M2D.available_variations.nominal_w_values_dict;
List_OP_Vars = ["InducedVoltage(Phase_A)", "InducedVoltage(Phase_B)", "InducedVoltage(Phase_C)"]
Mxwl_rawdata = M2D.post.get_solution_data(
        expressions=List_OP_Vars, 
        variations=Dict_vari,
        primary_sweep_variable="Time",
        );
for Var in List_OP_Vars:
        Var_rawdata = Mxwl_rawdata.data_real(Var);
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.12

### Installed packages

alabaster==1.0.0
annotated-types==0.7.0
ansys-api-edb==0.2.1
ansys-edb-core==0.2.1
ansys-pythonnet==3.1.0rc6
arrow==1.3.0
asgiref==3.9.1
asteval==1.0.6
astroid==3.3.11
asttokens==3.0.0
atomicwrites==1.4.1
attrs==25.3.0
autopep8==2.3.2
babel==2.17.0
backcall==0.2.0
bcrypt==4.3.0
beautifulsoup4==4.13.5
binaryornot==0.4.4
black==25.1.0
bleach==6.2.0
certifi==2025.8.3
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.4.3
click==8.2.1
cloudpickle==3.1.1
clr_loader==0.2.7.post0
colorama==0.4.6
comm==0.2.3
contourpy==1.3.3
cookiecutter==2.6.0
cryptography==45.0.6
cycler==0.12.1
debugpy==1.8.16
decorator==5.2.1
defusedxml==0.7.1
diff-match-patch==20241021
dill==0.4.0
Django==5.2.5
docstring-to-markdown==0.17
docutils==0.21.2
et_xmlfile==2.0.0
executing==2.2.0
fastjsonschema==2.21.2
flake8==7.3.0
fonttools==4.59.1
fpdf2==2.8.4
future==1.0.0
grpcio==1.74.0
idna==3.10
imagesize==1.4.1
importlib_metadata==8.7.0
inflection==0.5.1
intervaltree==3.1.0
invoke==2.2.0
ipykernel==6.30.1
ipython==8.37.0
ipython-genutils==0.2.0
ipython_pygments_lexers==1.1.1
isort==6.0.1
jaraco.classes==3.4.0
jaraco.context==6.0.1
jaraco.functools==4.3.0
jedi==0.19.2
jellyfish==1.2.0
Jinja2==3.1.6
jsonschema==4.25.1
jsonschema-specifications==2025.4.1
jupyter_client==8.6.3
jupyter_core==5.8.1
jupyterlab_pygments==0.3.0
keyring==25.6.0
kiwisolver==1.4.9
lazy-object-proxy==1.12.0
lmfit==1.3.4
markdown-it-py==4.0.0
MarkupSafe==3.0.2
matlabengine==25.1.2
matplotlib==3.10.5
matplotlib-inline==0.1.7
mccabe==0.7.0
mdurl==0.1.2
mistune==3.1.3
more-itertools==10.7.0
mypy_extensions==1.1.0
narwhals==2.1.2
nbclient==0.10.2
nbconvert==7.16.6
nbformat==5.10.4
nest-asyncio==1.6.0
numpy==2.2.6
numpydoc==1.9.0
olca-ipc==2.4.0
olca_schema==2.4.0
openpyxl==3.1.5
packaging==25.0
pandas==2.3.2
pandocfilters==1.5.1
paramiko==4.0.0
parso==0.8.5
pathspec==0.12.1
pexpect==4.9.0
pickleshare==0.7.5
pillow==11.3.0
platformdirs==4.3.8
plotly==6.3.0
pluggy==1.6.0
plumbum==1.9.0
pooch==1.8.2
prompt_toolkit==3.0.51
protobuf==4.25.8
psutil==7.0.0
ptyprocess==0.7.0
pure_eval==0.2.3
pyaedt==0.18.1
pycodestyle==2.14.0
pycparser==2.22
pydantic==2.11.7
pydantic_core==2.33.2
pydocstyle==6.3.0
pyedb==0.54.0
pyflakes==3.4.0
Pygments==2.19.2
pylint==3.3.8
pylint-venv==3.0.4
pyls-spyder==0.4.0
PyNaCl==1.5.0
pyparsing==3.2.3
PyQt5==5.15.11
PyQt5-Qt5==5.15.2
PyQt5_sip==12.17.0
PyQtWebEngine==5.15.7
PyQtWebEngine-Qt5==5.15.2
python-dateutil==2.9.0.post0
python-lsp-black==2.0.0
python-lsp-jsonrpc==1.1.2
python-lsp-server==1.13.0
python-slugify==8.0.4
pythonnet==3.0.5
pytoolconfig==1.3.1
pytz==2025.2
pyvista==0.46.2
pywin32==311
pywin32-ctypes==0.2.3
PyYAML==6.0.2
pyzmq==27.0.2
QDarkStyle==3.2.3
qstylizer==0.2.4
QtAwesome==1.4.0
qtconsole==5.6.1
QtPy==2.4.3
referencing==0.36.2
requests==2.32.5
rich==14.1.0
roman-numerals-py==3.1.0
rope==1.14.0
rpds-py==0.27.0
rpyc==6.0.2
rtree==1.4.1
scikit-rf==1.8.0
scipy==1.16.1
scooby==0.10.1
shapely==2.1.1
six==1.17.0
snowballstemmer==3.0.1
sortedcontainers==2.4.0
soupsieve==2.7
Sphinx==8.2.3
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
spyder==2.3.9
spyder-kernels==3.0.5
sqlparse==0.5.3
stack-data==0.6.3
text-unidecode==1.3
textdistance==4.6.3
three-merge==0.1.1
tinycss2==1.4.0
toml==0.10.2
tomli==2.2.1
tomli_w==1.2.0
tomlkit==0.13.3
tornado==6.5.2
traitlets==5.14.3
types-python-dateutil==2.9.0.20250822
typing-inspection==0.4.1
typing_extensions==4.14.1
tzdata==2025.2
ujson==5.11.0
uncertainties==3.2.3
urllib3==2.5.0
vtk==9.5.0
watchdog==6.0.0
wcwidth==0.2.13
webencodings==0.5.1
whatthepatch==1.0.7
wrapt==1.17.3
xlrd==2.0.2
xlsxwriter==3.2.5
yapf==0.43.0
zipp==3.23.0

**Comment by gmalinve** [comment]
Hi @mehs1006, The get_solution_data has been recently updated. I suggest you to upgrade your PyAEDT version to latest and retry.
Bear in mind that there is a new way of retrieving data from the SolutionData object and it is with get_expression_data. You can extract real, imag, mag etc data type of your quantity. Please look at the API reference for help: https://aedt.docs.pyansys.com/version/stable/API/visualization/_autosummary/ansys.aedt.core.visualization.post.solution_data.SolutionData.get_expression_data.html#get_expression_data.
